[theme]
primaryColor = "#A855F7"
backgroundColor = "#1C2137"
secondaryBackgroundColor = "#252B45"
textColor = "#E2E8F0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
